### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by biskfather** [ddainusshaa/dd-atmrobbery#1]
![2023 08 29-11 51](https://github.com/ddainusshaa/dd-atmrobbery/assets/80595080/2c8faaf6-1bad-458a-ba96-fbe041072761)

error is in image

**Comment by Mitchel** [comment]
Unfortunately have the same problem, temporarily took out those lines but then the rope does not stay on the ATM. If you also click 'X' a rope remains present in your hands and on your car.

**Comment by biskfather** [comment]
> Unfortunately have the same problem, temporarily took out those lines but then the rope does not stay on the ATM. If you also click 'X' a rope remains present in your hands and on your car.

hopefully script owner replies soon with a fix

**Comment by ddainusshaa** [comment]
Solved & Download again

**Comment by biskfather** [comment]
> Solved & Download again

working perfect now, thanks
